---
#- name: stop service cron on debian, if running
#  systemd:
#    name: firewalld
#    state: started
#    enabled: yes

#- name: check if firewalld is running
#  command: systemctl is-active firewalld
#  register: firewalld_result
#  changed_when: False
#  ignore_errors: True  # rc is 3 when firewalld is stopped

#- name: check_install / Allow ports for firewalld
#  firewalld:
#    port: "{{ item }}"
#    permanent: yes
#    immediate: yes
#    state: enabled
#  with_items: "{{ nginx_firewalld_port }}"
