---
- name: Define VM
  shell: >
    sudo virt-install \
    --name=cumulus01 \
    --vcpus=1 \
    --ram=1024 \
    --network bridge=br-isolate-rt \
    --network bridge=br-isolate-vm \
    --graphics none \
    --console pty,target_type=serial \
    --import \
    --disk  path=/var/lib/libvirt/images/kvm_pool/cumulus01.qcow2,format=qcow2

- name: wait vm create
  virt:
    name: cumulus01
    command: status
  register: result_wait
  until: result_wait.status == 'shutdown'
  failed_when: false
  ignore_errors: yes
  retries: 3
  delay: 30
#  delegate_to: "{{ host_ip }}"

- name: shutdown vm 
  virt:
    name: cumulus01
    command: shutdown
  failed_when: false
  ignore_errors: yes
  when: result_wait.status == 'running'

- name: shutdown vm status 
  virt:
    name: cumulus01
    command: status
  failed_when: false
  ignore_errors: yes
  register: result_shutdown
  until: result_shutdown.status == 'shutdown'
  when: result_wait.status == 'running'
  retries: 3
  delay: 10

- name: destroy vm 
  virt:
    name: cumulus01
    command: destroy
  failed_when: false
  ignore_errors: yes
  when: result_wait.status == 'running' and result_shutdown.status == 'running'

- name: destroy vm status
  virt:
    name: cumulus01
    command: status
  failed_when: false
  ignore_errors: yes
  register: result_destroy
  until: result_destroy.status == 'shutdown'
  when: result_wait.status == 'running' and result_shutdown.status == 'running'
  retries: 3
  delay: 10