---
- name: put kick start
  template:
    src: templates/ks.cfg.j2
    dest: /tmp/ks.cfg
    owner: root
    group: root
    mode: 0644

- name: Define VM
  shell: >
    virt-install \
    --name fedora33-test3 \
    --disk pool=kvm_pool,format=qcow2,size=100 \
    --vcpus 2 \
    --ram 4096 \
    --os-type linux \
    --os-variant fedora33 \
    --network bridge=br-isolate-vm \
    --graphics none \
    --console pty,target_type=serial \
    --location /tmp/Fedora-Server-dvd-x86_64-33-1.2.iso \
    --initrd-inject /tmp/ks.cfg \
    --extra-args \
      'inst.ks=file:/ks.cfg console=ttyS0,115200n8 serial'

- name: wait vm create
  virt:
    name: fedora33-test2
    command: status
  register: result
  until: result.status == 'shutdown'
  retries: 5
  delay: 60
#  delegate_to: "{{ host_ip }}"

- name: shutdown vm 
  virt:
    name: fedora33-test2
    command: shutdown
  when: result.status == 'running'

- name: destroy vm 
  virt:
    name: fedora33-test2
    command: shutdown
  when: result.status == 'running'