---
- name: Define VM
  shell: >
    virt-install \
    --name fedora33-test \
    --disk path=/home/kvm/kvm_pool/fedora33-test.img,size=20 \
    --vcpus 2 \
    --ram 4096 \
    --os-type linux \
    --os-variant fedora33 \
    --network bridge=private-mn \
    --graphics none \
    --console pty,target_type=serial \
    --location /home/fedora/Fedora-Server-dvd-x86_64-33-1.2.iso \
    --initrd-inject /home/fedora/template_ks.cfg \
    --extra-args \
      'inst.ks=file:/template_ks.cfg console=ttyS0,115200n8 serial'
- name: wait vm create
  virt:
    name: fedora33-test
    command: status
  register: result
  until: result.status == 'shutdown'
  retries: 50
  delay: 60
#  delegate_to: "{{ host_ip }}"