---
cloud_init_instance_id: '{{ inventory_hostname }}'
cloud_init_local_hostname: '{{ inventory_hostname }}.domain'
cloud_init_static: true
cloud_init_network: 192.168.10.0
cloud_init_netmask: 255.255.255.0
cloud_init_broadcast: 192.168.10.255
cloud_init_gateway: 192.168.10.254
cloud_init_dns_nameservers: 192.168.122.1
cloud_init_default_user: fedora
cloud_init_chpasswd: fedora
cloud_init_ssh_authorized_keys: AAAAB3NzaC1yc2EAAAADAQABAAABgQDWMA3+NlkGsrIrxEWEpJ7ZQrxL8K5CdqH1CdtvJ7gn4CWSLgFn2TJ1nbDXfDlzmyKccC6CeDcv4quiPuQE6mKiJFuTCC0iDyf31PJig6TuUbcqzKPko1I3llhVYePjZIF0IctwX8xRU8aS/1VYy93Jl/fdUngtBHsz6jeaIwGUMjT7t7eRdKv/GalFzRg/HStnvaVL7ucsQX8UnW3a7HzXJSdcqdSZWfJOsMbwPrpPMnEFBxMjhOMWCjj9TURbA5S8TNhmeYBXL6LMI6ZstofbczYDXFZsU4BoLMjwOlY3G4vjjK0MHkkHtqwL5nB3lZbOqUTI4hHIUXpU5bL5a0bO8DoEF3O2d2UDnjqbXXCNeQ3aZxOMAzfGeYsTqHr2f8tN/WSdJ4IP6hIICrY0Qujz3y2T14Ysk4zDlB4ZZaaOrI4xJJrxf1BeuWfAdMZgj5fFiViZXU2foaeR1GOjVzTWqdhYmf5FdbqTAl2rMPY7GIUFFt1zwoYyBeu4KtM2Pmc= fedora@localhost

virt_ram: 2048
virt_vcpus: 2
virt_os_type: linux
virt_os_variant: fedora33
virt_type: kvm
virt_disk: 20G

virt_net_name: k8s-net
virt_net_bridge_name: k8s-net
virt_net_forward: true
virt_net_forward_mode: nat
virt_net_ip_address: 10.0.0.1
virt_net_netmask: 255.255.255.0
virt_net_dhcp: false
virt_net_dhcp_range_start: 10.0.0.2
virt_net_dhcp_range_end: 10.0.0.254

virt_pool_name: kvm_pool
virt_pool_path: /var/lib/libvirt/images/kvm_pool

image_sha256sum: 7a2b3cc3bb3a92ce927e685d33efe8efd75577efbe207b267cb66f68afae7ce9
image_url: https://download.fedoraproject.org/pub/fedora/linux/releases/33/Cloud/x86_64/images/Fedora-Cloud-Base-33-1.2.x86_64.qcow2
image_download_path: /tmp/Fedora-Cloud-Base-33-1.2.x86_64.qcow2