---
- name: list pools
  virt_pool:
    command: list_pools
  register: result_pools

- name: exist pools
  debug:
    msg: "'{{ virt_pool_name }}' already exist"
  when: virt_pool_name in result_pools.list_pools

- block:
  - name: make pool directory
    file:
      path: "{{ virt_pool_path }}"
      state: directory
      owner: root
      group: root
      mode:  '0755'

  - name: pool define
    virt_pool:
      command: define
      name: '{{ virt_pool_name }}'
      xml: '{{ lookup("template", "templates/pool.xml.j2") }}'
    
  - name: pool start
    virt_pool:
      command: create
      name: '{{ virt_pool_name }}'

  - name: pool autostart
    virt_pool:
      autostart: yes
      name: '{{ virt_pool_name }}'

  when: virt_pool_name not in result_pools.list_pools